version: "3.3"
services:
  db:
    image: "postgres:12-alpine"
    ports:
      - "5432:5432"
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=secret
      - POSTGRES_MULTIPLE_DATABASES=db1,db2
